### ISSUE TITLE
Resource Packer

### ISSUE THREAD

**Issue by Neuromancer56** [minetest-mods/minetest-mods.github.io#10]
Mod Name: Resource Packer
Author: Neuromancer56
License: WTFPL

Goal of the mod is to create all/more of the Minecraft Nodes in minetest so full Minecraft resource packs can be used in Minetest
https://forum.minetest.net/viewtopic.php?f=9&t=10155

**Comment by sofar** [comment]
I have some concerns about this mod. 

- it's a modpack, but it's only one mod. The rules for minetest-mods are that modpacks are disallowed, and in this mod's case there really is no reason for making it a modpack.

- It seems it was coded up in 3 days and hasn't been touched ever since. The forum post describes 4 steps and only one finished. I also only see about a dozen textures mentioned in the code, while I would expect to see at least 50+ or so mentioned. My question is: is this really anywhere near usable?

**Comment by sofar** [comment]
@Neuromancer56 are you interested in addressing the issues raised above?

**Comment by Neuromancer56** [comment]
I'm not opposed to making it a non-mudpack.  The reason I suggested it for the minetest mods area because it would be best if it could incorporate nodes from any mods that correspond to Minecraft resource pack nodes.    Thus as mods are added to minetestmods, this mod could be kept up to date by incorporating the new nodes.  This mod will never be "finished" but even in its beginning state let's you use textures from resource packs.

**Comment by sofar** [comment]
I think this is better as a standalone conversion tool and not a mod. Mods are for server-side operation, and texture packs should be client-side.

https://forum.minetest.net/viewtopic.php?f=14&t=14271
