### ISSUE TITLE
Input about Vanessa's migrated mods to gitlab

### ISSUE THREAD

**Issue by sofar** [minetest-mods/minetest-mods.github.io#72]
This issue exists to solicit input about what to do about VE's mods, now that they have migrated to gitlab. @minetest-mods does not currently maintain a gitlab organization, and I personally see little value in doing so.

While I stand by the manifest that promises that mods should remain in the same location to offer longevity for users, in this case the presence of outdated code on github isn't helping users.

My personal view at this point (might change!) is that we should remove these mods from minetest-mods - if people can't submit PRs directly to minetest-mods mods, the reason for having them has vanished outside of the control of minetest-mods.

Input requested from @VanessaE, @Ekdohibs, @rubenwardy, @sfan5, @smalljoker.

Options I can see:
- remove (trivial)
- mirror (trivial)
- maintain (would require more active maintainers)
- something I haven't thought of

**Comment by SmallJoker** [comment]
Mirror them. If it's not possible: delete them.

**Comment by VanessaE** [comment]
Agreed with @SmallJoker

**Comment by paramat** [comment]
Whatever VanessaE wants.

**Comment by sofar** [comment]
I'm not interested in running a mirror service myself, and I don't think I should have to. If @vanessae wants to mirror them, I'm OK with that. I'll need to know which repos that are, though.

Alternatively, your choice, we just delete them from minetest-mods.

**Comment by sofar** [comment]
@VanessaE please provide the list of mods here that need removal.

**Comment by DS-Minetest** [comment]
Removing all the repositories could arise some problems with links. Eg. I've often posted links to the pipeworks wiki on github.

**Comment by VanessaE** [comment]
* https://github.com/minetest-mods/biome_lib --> https://gitlab.com/VanessaE/biome_lib
* https://github.com/minetest-mods/homedecor_modpack --> https://gitlab.com/VanessaE/homedecor_modpack
* https://github.com/minetest-mods/moretrees --> https://gitlab.com/VanessaE/moretrees
* https://github.com/minetest-mods/pipeworks --> https://gitlab.com/VanessaE/pipeworks
* https://github.com/minetest-mods/unifieddyes --> https://gitlab.com/VanessaE/unifieddyes
* https://github.com/minetest-mods/signs_lib --> https://gitlab.com/VanessaE/signs_lib
* https://github.com/minetest-mods/plantlife_modpack --> https://gitlab.com/VanessaE/plantlife_modpack
* https://github.com/minetest-mods/coloredwood --> https://gitlab.com/VanessaE/coloredwood
* https://github.com/minetest-mods/nixie_tubes --> https://gitlab.com/VanessaE/nixie_tubes
* https://github.com/minetest-mods/round_trunks --> https://gitlab.com/VanessaE/round_trunks

These below didn't start out as "mine", but I took them over long ago, or otherwise somehow got snookered into being the primary maintainer, :smiley: so my Gitlab repos are the closest to "official" as far as I know:

* https://github.com/minetest-mods/blox --> https://gitlab.com/VanessaE/blox
* https://github.com/minetest-mods/gloopblocks --> https://gitlab.com/VanessaE/gloopblocks
* https://github.com/minetest-mods/currency --> https://gitlab.com/VanessaE/currency
* https://github.com/minetest-mods/ilights --> https://gitlab.com/VanessaE/ilights

While browsing the list, I ran across Dan's old prefab mod, https://github.com/minetest-mods/prefab ... but this mod is completely abandoned and outdated now.  @cheapie forked and reworked it, https://cheapiesystems.com/git/prefab_redo/ ...  her fork should be considered the closest to "official".

Also, I ran across Zeg9's steel mod, https://github.com/minetest-mods/steel ... I'm not the mod's maintainer, and Zeg9 is long gone from MT, but it seems I've been the main contributor in the past couple years.  I do not have a Gitlab repo for it, and am not sure what should be done, if anything.

**Comment by sofar** [comment]
@cheapie your choice if you want: we can delete minetest-mods/prefab, or you can choose to maintain it. Up to you. Please tell us what you want, though.

**Comment by sofar** [comment]
@VanessaE you're welcome to clone `steel` back to gitlab if you prefer. Just let me know.

**Comment by sofar** [comment]
@VanessaE Please scan the forum for links, as usual. I will update the PRMS to add your gitlab URLs so those are included.

**Comment by VanessaE** [comment]
> @VanessaE you're welcome to clone steel back to gitlab if you prefer. Just let me know.

I've done so.

> @VanessaE Please scan the forum for links, as usual. I will update the PRMS to add your gitlab URLs so those are included.

I think I already took care of everything I could after I moved initially, but I'll give it another look.

**Comment by cheapie** [comment]
> @cheapie your choice if you want: we can delete minetest-mods/prefab, or you can choose to maintain it. Up to you. Please tell us what you want, though.

minetest-mods/prefab and my prefab_redo are not the same mod.

**Comment by bell07** [comment]
Sad the Microsoft did split the Minetest modder comunity by buying github.
Maybe https://gitlab.com/minetest-mods can be used for mods owned by MS-haters?
Maybe the Gitlab mirrorong service can be used? https://docs.gitlab.com/ee/workflow/repository_mirroring.html
Eather push to github or pull to gitlab is possible.

**Comment by VanessaE** [comment]
> minetest-mods/prefab and my prefab_redo are not the same mod.

I recommended discarding the old prefab because it's old and crusty now and yours makes a good drop-in replacement for it :smiley:

**Comment by sofar** [comment]
>Maybe https://gitlab.com/minetest-mods can be used for mods owned by
>MS-haters?
>Maybe the Gitlab mirrorong service can be used?
>https://docs.gitlab.com/ee/workflow/repository_mirroring.html
>Eather push to github or pull to gitlab is possible.

Off topic. Please open a new issue.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sofar** [comment]
If they're not the same (unrelated code base) then there's no reason to remove it - forum links are entirely reasonable to be changed if minetest-mods/prefab is old, too.

**Comment by sofar** [comment]
Closing since no action left. Open new issues for further changes needed on an individual basis!
