### ISSUE TITLE
New mod request:Real_g

### ISSUE THREAD

**Issue by squidKid-deluxe** [minetest-mods/minetest-mods.github.io#98]
Mod Name: [real_g](https://github.com/squidKid-deluxe/real_g)
Author: squidKid-deluxe
License:See [license.txt](https://github.com/squidKid-deluxe/real_g/blob/master/LICENSE)

The *real_g* mod provides gravity in minetest similar to the gravity in the real-world: as you get higher above sea level, your gravity decreases, and as you get lower your gravity increases(to a maximum of 1, eg. normal minetest gravity)

**Comment by sofar** [comment]
Um, the license is fine of course, but, geologically speaking, it is missing something.

As you decend into earth's depth, gravity **decreases**. That is because a large part of earth's mass that forms earth's gravity is **now above you**. 

So, if you want to make your mod even more interesting, and, scientifically more correct, you should also reduce gravity for players as they descend into the depths of the earth.

Second, the way you coded this isn't appropriate for sharing. You're using an ABM, which you shouldn't do for player object manipulations. A globalstep timer would be appropriate. I am concerned your gravity function also is unsuitable for any sort of elevations that might occur normally in many mods - you make gravity lower too fast I think.

The mod also only works for `singleplayer` which is useless for anyone deploying this on a server.

All those things would need fixing - I like the idea but this isn't mature enough code, IMHO.

**Comment by squidKid-deluxe** [comment]
Alright, I'll work on the stuff you mentioned. I was thinking about making the gravity less 'speedy' in decreaseing as you went up. Also, why doesn't the mod work on server? I'm kind of confused there.

**Comment by sofar** [comment]
You're only modifying the `singleplayer` player. No other player will be affected. Again, you shouldn't use an ABM either. I would suggest a globaltimer instead where you loop over all connected players every ~5 seconds or so, as well as capturing on teleport events.

**Comment by squidKid-deluxe** [comment]
Why so long? I was thinking more like every two seconds, as otherwise, when falling quickly, there would seem to be a lag.

May 20, 2020, 3:34 PM by notifications@github.com:

>
>
>
>
> You're only modifying the > singleplayer>  player. No other player will be affected. Again, you shouldn't use an ABM either. I would suggest a globaltimer instead where you loop over all connected players every ~5 seconds or so, as well as capturing on teleport events.
>
>

**Comment by squidKid-deluxe** [comment]
Everything fixed!!!!! I have set the globalstep timer to once every four (4) seconds.

**Comment by sofar** [comment]
This line isn't needed:

`	gravity_timer = gravity_timer + dtime`

Other than that, this looks pretty good. You could make gravity a straight function with `Math.abs(y)` and remove all the `if... then` parts, but, that's nitpicking really.

Do you still want to have your mod moved into `minetest-mods`?

**Comment by squidKid-deluxe** [comment]
> Do you still want to have your mod moved into minetest-mods?

Way!! That would be so awesome!

**Comment by sofar** [comment]
@squidKid-deluxe the way to move it is that you transfer the repository to me (`sofar`). Then I will transfer the repo into `mintest-mods` since this can't be done directly. During and after this move you keep access and users are redirected to the right place at all times. When you initiate the transfer I will get an email and handle it as soon as I see it.

**Comment by squidKid-deluxe** [comment]
### **_Awesome!_**
